name: event_planner
description: "Swivel Event Planner"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  cloud_functions: ^5.0.4
  firebase_storage: ^12.1.3
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2

  #bloc supported plugins
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5

  get: ^4.6.5
  auto_route: ^7.8.4
  gap: ^3.0.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  flutter_lints: ^4.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 29
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/
    - assets/images/icon_images/
    - assets/images/svg/


